using Newtonsoft.Json;

namespace SteamAuth
{
    /// <summary>
    ///     Holds necessary user credential information for the process of logging in to the user account
    /// </summary>
    public class LoginCredentials
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="LoginCredentials" /> class.
        /// </summary>
        /// <param name="username">The username of the account.</param>
        /// <param name="password">The password of the account.</param>
        /// <param name="twoFactorAuthenticationCode">The two factor authentication code for the login process.</param>
        /// <param name="captchaCode">The captcha code for the login process.</param>
        /// <param name="emailVerificationCode">The email verification code for the login process.</param>
        [JsonConstructor]
        public LoginCredentials(
            string username,
            string password,
            string twoFactorAuthenticationCode = null,
            string captchaCode = null,
            string emailVerificationCode = null)
        {
            UserName = username;
            Password = password;
            TwoFactorAuthenticationCode = twoFactorAuthenticationCode;
            CaptchaCode = captchaCode;
            EmailVerificationCode = emailVerificationCode;
        }

        /// <summary>
        ///     Gets or sets the captcha code required by the login process.
        /// </summary>
        /// <value>
        ///     The captcha code interpreted from the captcha image.
        /// </value>
        [JsonIgnore]
        public string CaptchaCode { get; set; }

        /// <summary>
        ///     Gets or sets the email verification code send to the user account registered email address.
        /// </summary>
        /// <value>
        ///     The email verification code read from the received email.
        /// </value>
        [JsonIgnore]
        public string EmailVerificationCode { get; set; }

        /// <summary>
        ///     Gets the password of the Steam account.
        /// </summary>
        /// <value>
        ///     The password of the Steam account.
        /// </value>
        public string Password { get; }

        /// <summary>
        ///     Gets or sets the two factor authentication code required by the login process.
        /// </summary>
        /// <value>
        ///     The two factor authentication code generated by the account's registered Authenticator
        /// </value>
        [JsonIgnore]
        public string TwoFactorAuthenticationCode { get; set; }

        /// <summary>
        ///     Gets the username of the account in Steam network
        /// </summary>
        /// <value>
        ///     The Steam user name.
        /// </value>
        public string UserName { get; }
    }
}